#!/bin/zsh

clear 

colors=("\033[30m" "\033[34m" "\033[32m" "\033[36m" "\033[31m" "\033[35m" "\033[33m" "\033[37m" "\033[1;30m" "\033[1;34m" "\033[1;32m" "\033[1;36m" "\033[1;31m" "\033[1;35m" "\033[1;33m" "\033[1;37m") 
white="\033[0m"
while (( 1 ))
do
	id=$RANDOM%2
	if (( id == 0 )); then
		color=${colors[$RANDOM % 16]}
		echo -n "$color$RANDOM$white"
	else
		color=${colors[$RANDOM % 16]}
		echo -n "$color"
		./random_word
		echo -n "$white"
	fi
		sleep 0.009
done
